name: Publish
on:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check format
        run: deno fmt --check

      - name: Check lint
        run: deno lint

      - uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: fcdd1888451bc144a068ba562422291e57291377485383ffbe61b9828aed0b7d
        with:
          coverageCommand: deno run ci
          coverageLocations: |
            ${{github.workspace}}/*.lcov:lcov

  publish:
    runs-on: ubuntu-latest
    needs: [checks]

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Publish package
        run: deno publish
